import LegalHeader from "@/components/legal/LegalHeader";
import LegalFooter from "@/components/legal/LegalFooter";
import { legalStyles as s } from "@/components/legal/legalStyles";
import { LEGAL_ENTITY, LEGAL_DATES } from "@/lib/legal/companyInfo";

export const metadata = { title: "Privacy Notice — TenderProc" };

export default function PrivacyPage() {
  return (
    <div>
      <LegalHeader />
      <main className="max-w-3xl mx-auto px-6 py-16">
        <p className="text-xs font-semibold uppercase tracking-[0.15em] text-inkDim">Legal</p>
        <h1 className="font-display font-bold text-4xl text-ink mt-2 tracking-tight">Privacy Notice</h1>
        <p className="text-sm text-inkDim mt-3">Last updated: {LEGAL_DATES.lastUpdated}</p>

        <p className={s.p}>
          This notice explains what personal data TenderProc collects, why, and what rights you have over it under
          the EU General Data Protection Regulation (GDPR) and Belgian data protection law. It applies to visitors
          of our website and users of the TenderProc app.
        </p>

        <h2 className={s.h2}>1. Who is responsible for your data</h2>
        <p className={s.p}>
          The data controller is <strong className={s.strong}>{LEGAL_ENTITY.name}</strong>, commercial registration /
          tax number {LEGAL_ENTITY.companyNumber}. For any question about this notice or
          to exercise your rights, contact us at{" "}
          <a href={`mailto:${LEGAL_ENTITY.contactEmail}`}>{LEGAL_ENTITY.contactEmail}</a>.
        </p>
        <p className={s.p}>
          We&apos;re established outside the European Union but offer the Service to businesses in Belgium and the
          EU, so this notice, and GDPR itself, still applies to how we handle your data (GDPR Art. 3(2)).
        </p>

        <h2 className={s.h2}>2. What we collect</h2>
        <p className={s.p}>
          <strong className={s.strong}>Account data:</strong> your email address and password (stored hashed by
          our authentication provider, Supabase — we never see the plaintext password).
        </p>
        <p className={s.p}>
          <strong className={s.strong}>Company profile:</strong> company name, address, size, sectors, description,
          website, employee count, regions served and languages served — collected at signup and editable on your
          Company page.
        </p>
        <p className={s.p}>
          <strong className={s.strong}>Company knowledge base:</strong> the services you offer, certifications,
          past references (which may include contract values), and supporting documents you upload. This is used
          to generate match scores and eligibility checks, and — only where you choose to — as source material for
          AI-drafted bid responses.
        </p>
        <p className={s.p}>
          <strong className={s.strong}>Tenders and bids:</strong> tenders you upload or track, the requirements and
          award criteria we extract from them, your bid workspace data (status, checklists, uploaded bid
          documents, AI-drafted response text), and — if you record it — the outcome of a bid, which may include
          competitively sensitive figures like winning price or your own score.
        </p>
        <p className={s.p}>
          <strong className={s.strong}>Technical data:</strong> standard request data (IP address, browser
          user-agent) generated by using a web app, session cookies used to keep you signed in, and a cookie
          storing your language preference. We don&apos;t run third-party advertising or analytics trackers.
        </p>

        <h2 className={s.h2}>3. Why we process it, and on what legal basis</h2>
        <ul className={s.ul}>
          <li>
            <strong className={s.strong}>Providing the Service</strong> — creating your account, matching tenders
            to your profile, running eligibility checks, generating draft bid responses, and running your bid
            workspace. Legal basis: performance of our contract with you (Art. 6(1)(b) GDPR).
          </li>
          <li>
            <strong className={s.strong}>Billing</strong> — processing your subscription via Paddle, and keeping
            records required for accounting and tax law. Legal basis: contract performance and legal obligation
            (Art. 6(1)(b) and (c) GDPR).
          </li>
          <li>
            <strong className={s.strong}>Service notifications</strong> — sending the tender digest email for
            sectors you&apos;ve selected. Legal basis: legitimate interest in operating the feature you
            configured (Art. 6(1)(f) GDPR); you can turn this off in your preferences at any time.
          </li>
          <li>
            <strong className={s.strong}>Security and abuse prevention</strong> — protecting accounts and the
            Service from unauthorized access. Legal basis: legitimate interest (Art. 6(1)(f) GDPR).
          </li>
          <li>
            <strong className={s.strong}>Legal compliance</strong> — responding to lawful requests, tax and
            accounting record-keeping. Legal basis: legal obligation (Art. 6(1)(c) GDPR).
          </li>
        </ul>
        <p className={s.p}>
          AI-assisted outputs (match scores, eligibility checks, drafted text) are generated to help you, not to
          make decisions about you — TenderProc doesn&apos;t use automated processing to make decisions that
          produce legal or similarly significant effects concerning you within the meaning of Art. 22 GDPR. A
          human — you — always reviews and decides before anything is submitted to a contracting authority.
        </p>

        <h2 className={s.h2}>4. Who we share it with</h2>
        <p className={s.p}>
          We share personal data with the following processors, each bound by a data processing agreement, and
          only to the extent needed to provide the Service:
        </p>
        <ul className={s.ul}>
          <li>
            <strong className={s.strong}>Supabase</strong> — hosts our database, authentication and file storage.
            Project region: {LEGAL_ENTITY.supabaseRegion}.
          </li>
          <li>
            <strong className={s.strong}>Anthropic</strong> — processes tender and company text you submit to
            generate match scores, eligibility checks, and draft bid responses. Anthropic is based in the United
            States; transfers are covered by Standard Contractual Clauses or an equivalent safeguard.
          </li>
          <li>
            <strong className={s.strong}>Resend</strong> — delivers the tender-digest email and other
            transactional emails.
          </li>
          <li>
            <strong className={s.strong}>Paddle</strong> — processes payments and acts as Merchant of Record for
            paid subscriptions; Paddle receives the billing details needed to process your payment (Paddle, not
            us, holds your card details).
          </li>
        </ul>
        <p className={s.p}>
          Tender and award data flowing the other way — from the EU&apos;s TED database and Belgium&apos;s
          e-Procurement/BOSA platform into TenderProc — is public procurement data, not your personal data; we
          don&apos;t send your data to these sources.
        </p>
        <p className={s.p}>
          We don&apos;t sell personal data, and we don&apos;t share it with third parties for their own marketing
          purposes.
        </p>

        <h2 className={s.h2}>5. International transfers</h2>
        <p className={s.p}>
          Your data leaves the EU/EEA in more than one way here, and we want to be direct about that rather than
          bury it: our database and file storage (Supabase) are hosted in {LEGAL_ENTITY.supabaseRegion}, our AI
          processing provider (Anthropic) is based in the United States, and {LEGAL_ENTITY.name} itself, as
          controller, is established outside the EU/EEA. For each of these transfers, we rely on the European
          Commission&apos;s Standard Contractual Clauses or another lawful transfer mechanism recognized under
          GDPR Chapter V to protect your data. You can ask us for a copy of the relevant safeguard by contacting
          us at <a href={`mailto:${LEGAL_ENTITY.contactEmail}`}>{LEGAL_ENTITY.contactEmail}</a>.
        </p>

        <h2 className={s.h2}>6. How long we keep it</h2>
        <p className={s.p}>
          We keep your account and workspace data for as long as your account is active. If you delete your
          account, we delete or anonymize your personal data within a reasonable period, except data we&apos;re
          required to keep for longer — for example, billing and invoice records, which we retain for the period
          required by Belgian accounting and tax law.
        </p>

        <h2 className={s.h2}>7. Your rights</h2>
        <p className={s.p}>Under GDPR, you have the right to:</p>
        <ul className={s.ul}>
          <li>Access the personal data we hold about you;</li>
          <li>Correct inaccurate data;</li>
          <li>Ask us to delete your data (subject to our legal retention obligations, e.g. for invoices);</li>
          <li>Restrict or object to certain processing;</li>
          <li>Receive your data in a portable format;</li>
          <li>Withdraw consent at any time, where processing is based on consent;</li>
          <li>
            Lodge a complaint with the Belgian Data Protection Authority (Gegevensbeschermingsautoriteit /
            Autorité de protection des données) or your own EU supervisory authority.
          </li>
        </ul>
        <p className={s.p}>
          To exercise any of these rights, contact us at{" "}
          <a href={`mailto:${LEGAL_ENTITY.contactEmail}`}>{LEGAL_ENTITY.contactEmail}</a>. We may need to verify
          your identity before acting on a request.
        </p>

        <h2 className={s.h2}>8. Cookies</h2>
        <p className={s.p}>
          We use only strictly necessary cookies: one to keep you signed in (set by Supabase authentication) and
          one to remember your language preference. We don&apos;t use advertising or third-party analytics
          cookies. Because these cookies are strictly necessary for the Service to function, we don&apos;t show a
          cookie consent banner for them.
        </p>

        <h2 className={s.h2}>9. Security</h2>
        <p className={s.p}>
          Data in transit is encrypted (HTTPS). Access to your data within the Service is scoped to your own
          account through row-level security enforced at the database layer — by default, no other customer&apos;s
          account can query your data. Access by TenderProc staff is limited to what&apos;s needed for support and
          operating the Service.
        </p>

        <h2 className={s.h2}>10. Children</h2>
        <p className={s.p}>
          TenderProc is a business-to-business service and isn&apos;t directed at, or knowingly used by, children.
        </p>

        <h2 className={s.h2}>11. Changes to this notice</h2>
        <p className={s.p}>
          We may update this notice from time to time. If a change is material, we&apos;ll make reasonable efforts
          to notify you before it takes effect.
        </p>
      </main>
      <LegalFooter />
    </div>
  );
}
