import LegalHeader from "@/components/legal/LegalHeader";
import LegalFooter from "@/components/legal/LegalFooter";
import { legalStyles as s } from "@/components/legal/legalStyles";
import { LEGAL_ENTITY, LEGAL_DATES } from "@/lib/legal/companyInfo";

export const metadata = { title: "Terms of Service — TenderProc" };

export default function TermsPage() {
  return (
    <div>
      <LegalHeader />
      <main className="max-w-3xl mx-auto px-6 py-16">
        <p className="text-xs font-semibold uppercase tracking-[0.15em] text-inkDim">Legal</p>
        <h1 className="font-display font-bold text-4xl text-ink mt-2 tracking-tight">Terms of Service</h1>
        <p className="text-sm text-inkDim mt-3">Last updated: {LEGAL_DATES.lastUpdated}</p>

        <p className={s.p}>
          These Terms of Service (&quot;<strong className={s.strong}>Terms</strong>&quot;) govern access to and use
          of TenderProc (the &quot;<strong className={s.strong}>Service</strong>&quot;), operated by{" "}
          <strong className={s.strong}>{LEGAL_ENTITY.name}</strong>, {LEGAL_ENTITY.address}, commercial
          registration / tax number {LEGAL_ENTITY.companyNumber} (&quot;
          <strong className={s.strong}>TenderProc</strong>&quot;,
          &quot;we&quot;, &quot;us&quot;). By creating an account or using the Service, you agree to these Terms.
          If you don&apos;t agree, don&apos;t use the Service.
        </p>

        <h2 className={s.h2}>1. What TenderProc is</h2>
        <p className={s.p}>
          TenderProc is a B2B software service that helps businesses discover, screen and prepare bids for public
          procurement tenders in Belgium. It surfaces tender notices from public sources, generates AI-assisted
          match scores, eligibility checks and draft bid responses, and provides a workspace to track bids from
          screening through submission.
        </p>
        <p className={s.p}>
          <strong className={s.strong}>The Service is a decision-support tool, not a substitute for your own
          judgment or professional advice.</strong> Match scores, eligibility checks, extracted requirements and
          AI-drafted responses are estimates generated by automated processing and may be incomplete, out of date
          or wrong. You are solely responsible for independently verifying tender requirements, deadlines,
          eligibility criteria and the content of anything you submit to a contracting authority before you submit
          it. TenderProc is not liable for a missed deadline, a disqualified bid, or a lost contract that results
          from relying on the Service without that independent verification.
        </p>

        <h2 className={s.h2}>2. Accounts</h2>
        <p className={s.p}>
          You must provide accurate information when creating an account and keep your login credentials
          confidential. You&apos;re responsible for all activity under your account. The Service is intended for
          use by businesses and professionals acting in a business capacity, not consumers acting for purely
          personal purposes. You must be authorized to act on behalf of the company you register.
        </p>

        <h2 className={s.h2}>3. Plans, billing and cancellation</h2>
        <p className={s.p}>
          TenderProc offers a Free plan and paid Pro/Premium plans, billed monthly. Paid plans are sold and
          collected by <strong className={s.strong}>Paddle</strong>, our payment provider, who acts as the{" "}
          <strong className={s.strong}>Merchant of Record</strong> for these transactions — Paddle is the seller of
          record, handles payment processing, and collects and remits applicable sales tax/VAT. Your purchase is
          also subject to Paddle&apos;s own buyer terms, presented to you at checkout.
        </p>
        <p className={s.p}>
          Subscriptions renew automatically each month until cancelled. You can cancel anytime from the Billing
          page in the app; cancellation stops future renewals but doesn&apos;t end your current paid period early —
          you keep paid-tier access until it expires, then your account moves to the Free plan. See our{" "}
          <a href="/refund" className="underline">
            Refund Policy
          </a>{" "}
          for how refunds are handled.
        </p>
        <p className={s.p}>
          If a payment fails, we may place your account into a grace period during which paid-tier access
          continues while you update your payment method; if payment isn&apos;t resolved, your account is moved to
          the Free plan.
        </p>

        <h2 className={s.h2}>4. Acceptable use</h2>
        <p className={s.p}>You agree not to:</p>
        <ul className={s.ul}>
          <li>Use the Service to violate any applicable law, including public procurement law;</li>
          <li>
            Scrape, systematically extract, resell, or redistribute tender data or other content from the Service
            except through features we provide for that purpose;
          </li>
          <li>Attempt to circumvent usage limits tied to your plan, or share one account across unrelated businesses;</li>
          <li>Upload content you don&apos;t have the right to upload, or that infringes a third party&apos;s rights;</li>
          <li>
            Interfere with the Service&apos;s operation, probe its security, or use it to build a competing
            product;
          </li>
          <li>Misrepresent AI-generated content from the Service as independently verified fact in a bid submission without review.</li>
        </ul>

        <h2 className={s.h2}>5. Your content</h2>
        <p className={s.p}>
          You retain ownership of the company information, documents and other content you upload or enter
          (&quot;<strong className={s.strong}>Your Content</strong>&quot;). You grant us a license to host,
          process and analyze Your Content — including sending relevant excerpts to our AI processing provider —
          solely to provide and improve the Service for you. We don&apos;t sell Your Content, and we don&apos;t use
          it to train third-party models beyond what&apos;s described in our{" "}
          <a href="/privacy" className="underline">
            Privacy Notice
          </a>
          . You&apos;re responsible for having the rights to anything you upload, including any third-party
          references, certifications, or documents describing subcontractors or partners.
        </p>

        <h2 className={s.h2}>6. Third-party tender data</h2>
        <p className={s.p}>
          Tender notices and award data shown in the Service are sourced from public databases (including the
          EU&apos;s TED and Belgium&apos;s e-Procurement/BOSA platform). We don&apos;t control these sources and
          don&apos;t guarantee their accuracy, completeness, or timeliness. Always confirm tender details against
          the official notice and the contracting authority&apos;s own channel before acting on them.
        </p>

        <h2 className={s.h2}>7. Intellectual property</h2>
        <p className={s.p}>
          The Service, its software, design and TenderProc branding are owned by {LEGAL_ENTITY.name} or its
          licensors and are protected by intellectual property law. Nothing in these Terms transfers ownership of
          the Service to you; you get a limited, non-exclusive, non-transferable right to use it in accordance
          with these Terms.
        </p>

        <h2 className={s.h2}>8. Disclaimers</h2>
        <p className={s.p}>
          The Service is provided &quot;as is&quot; and &quot;as available.&quot; To the fullest extent permitted
          by law, we disclaim all warranties, express or implied, including fitness for a particular purpose and
          non-infringement. We don&apos;t warrant that the Service will be uninterrupted, error-free, or that AI
          outputs will be accurate. Nothing in this section limits any warranty or right that can&apos;t lawfully
          be excluded.
        </p>

        <h2 className={s.h2}>9. Limitation of liability</h2>
        <p className={s.p}>
          To the fullest extent permitted by law, TenderProc won&apos;t be liable for indirect, incidental,
          consequential or lost-profit damages, including a lost contract, lost bid, or lost revenue, arising from
          use of the Service. Our total liability for any claim arising from these Terms or the Service is limited
          to the amount you paid us in the 12 months before the claim arose. This section doesn&apos;t limit
          liability that can&apos;t be excluded under applicable law (for example, liability for our own gross
          negligence, willful misconduct, or death or personal injury we cause).
        </p>

        <h2 className={s.h2}>10. Termination</h2>
        <p className={s.p}>
          You may stop using the Service and delete your account at any time. We may suspend or terminate your
          account for breach of these Terms, non-payment, or if required by law, with notice where reasonably
          possible. Sections that by their nature should survive termination (ownership, disclaimers, limitation
          of liability, governing law) do.
        </p>

        <h2 className={s.h2}>11. Changes to these Terms</h2>
        <p className={s.p}>
          We may update these Terms from time to time. If a change is material, we&apos;ll make reasonable efforts
          to notify you (for example, by email or an in-app notice) before it takes effect. Continued use of the
          Service after a change takes effect means you accept the updated Terms.
        </p>

        <h2 className={s.h2}>12. Governing law</h2>
        <p className={s.p}>
          These Terms are governed by the laws of {LEGAL_ENTITY.jurisdiction}, without regard to conflict-of-law
          rules. Any dispute not resolved informally will be subject to the exclusive jurisdiction of the courts of{" "}
          {LEGAL_ENTITY.jurisdiction}, except where applicable consumer-protection law gives you the right to bring
          a claim in your own place of residence.
        </p>

        <h2 className={s.h2}>13. Contact</h2>
        <p className={s.p}>
          Questions about these Terms: <a href={`mailto:${LEGAL_ENTITY.contactEmail}`}>{LEGAL_ENTITY.contactEmail}</a>.
        </p>
      </main>
      <LegalFooter />
    </div>
  );
}
